apiVersion: apps/v1
kind: Deployment
metadata:
  name: mana-food-app
  namespace: default
  labels:
    app: mana-food-app
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mana-food-app
  template:
    metadata:
      labels:
        app: mana-food-app
        version: v1
    spec:
      containers:
      - name: app
        image: ghcr.io/mana-food/mana-food-clean-architecture:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        envFrom:
        - configMapRef:
            name: mana-food-config
        - secretRef:
            name: mana-food-secrets
        startupProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 5
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 10
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 20
          failureThreshold: 3